language: java

jdk:
  - oraclejdk8
  
after_success:
  - |
    echo '
    <?xml version="1.0" encoding="UTF-8"?>
    <settings xmlns="http://maven.apache.org/SETTINGS/1.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0 https://maven.apache.org/xsd/settings-1.0.0.xsd">
        <servers>
          <server>
              <id>ossrh</id>
              <username>${env.SONATYPE_USERNAME}</username>
              <password>${env.SONATYPE_PASSWORD}</password>
          </server>
        </servers>
    </settings>' > ~/.m2/settings_boxfish-commons-web-model.xml
  - mvn clean deploy --settings ~/.m2/settings_boxfish-commons-web-model.xml
